package com.underworld.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** GENERATED by tools/gen_assets.py - edit the script, not this file. */
@SuppressWarnings("unused")
public final class SpectralBoltGeometry {
	private SpectralBoltGeometry() {
	}

	public static LayerDefinition create() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition p_root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -0.5F, -7.0F, 1.0F, 1.0F, 14.0F, new CubeDeformation(0.0F)).texOffs(38, 0).addBox(-1.5F, -1.5F, -10.0F, 3.0F, 3.0F, 3.0F, new CubeDeformation(-0.5F)).texOffs(50, 0).addBox(-2.0F, -0.5F, 4.0F, 4.0F, 1.0F, 3.0F, new CubeDeformation(-0.1F)).texOffs(30, 0).addBox(-0.5F, -2.0F, 4.0F, 1.0F, 4.0F, 3.0F, new CubeDeformation(-0.1F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
		return LayerDefinition.create(mesh, 64, 32);
	}
}
