package com.underworld.registry;

import com.underworld.Underworld;
import com.underworld.block.CuriosityBlock;
import java.util.List;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.phys.shapes.VoxelShape;

/** The Collector's jars and bottles. Models/textures are generated by tools/gen_assets.py. */
public final class ModBlocks {
	public static final Block SOUL_JAR = jar("soul_jar", Block.column(8, 0, 11), 7);
	public static final Block SPECIMEN_JAR = jar("specimen_jar", Block.column(10, 0, 13), 0);
	public static final Block DUSTY_JAR = jar("dusty_jar", Block.column(8, 0, 9), 0);
	public static final Block TALL_POTION = jar("tall_potion", Block.column(8, 0, 14), 3);
	public static final Block POTION_BOTTLES = jar("potion_bottles", Block.column(14, 0, 9), 2);

	public static final List<Block> CURIOSITIES = List.of(SOUL_JAR, SPECIMEN_JAR, DUSTY_JAR, TALL_POTION, POTION_BOTTLES);

	private ModBlocks() {
	}

	private static Block jar(String name, VoxelShape shape, int light) {
		ResourceKey<Block> key = ResourceKey.create(Registries.BLOCK, Underworld.id(name));
		BlockBehaviour.Properties props = BlockBehaviour.Properties.of()
			.mapColor(MapColor.NONE)
			.strength(0.3F)
			.sound(SoundType.GLASS)
			.noOcclusion()
			.lightLevel(s -> light)
			.setId(key);
		Block block = Registry.register(BuiltInRegistries.BLOCK, key, new CuriosityBlock(shape, props));
		ModItems.registerBlockItem(name, p -> new BlockItem(block, p.useBlockDescriptionPrefix()));
		return block;
	}

	public static void init() {
	}
}
