"""Regenerates every entity texture and ModelMeshes.java from the model specs.  Run: python tools/art/build.py"""
import os
from PIL import Image
import gravebound, wisp, guard, death, minor, npcs, hunter, folk
import sys

# ---- guard -------------------------------------------------------------------------------------------------------------
# This writes every file it knows from the definitions in these scripts, as they stood at DeathBound 1.0.0 (Oct 6).
# Everything changed in the repo since (stories, advancements, new charms, Death's Requiem, the 16px textures, quest text)
# would be overwritten by the 1.0.0 version. Port the change into the scripts first, then run with DB_REGEN=1.
if os.environ.get('DB_REGEN') != '1':
    sys.exit(__file__ + ': refusing to run without DB_REGEN=1 (it would overwrite newer resources; see the note above).')


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
TEX = os.path.join(ROOT, 'src/main/resources/assets/deathbound/textures/entity')
JAVA = os.path.join(ROOT, 'src/client/java/com/deathbound/client/model/ModelMeshes.java')
os.makedirs(TEX, exist_ok=True)


def save(img, name):
    Image.fromarray(img, 'RGBA').save(os.path.join(TEX, name + '.png'))


models = []  # (java method, model)
# variants share one mesh (UV packing depends only on cube sizes), so each is just another texture pair
graves = {v: gravebound.build(v) for v in ('shrouded', 'bare', 'knight', 'charred')}
for v, gm in graves.items():
    save(gm.img, 'gravebound_' + v)
    save(gm.glow, 'gravebound_' + v + '_glow')
models.append(('gravebound', graves['shrouded']))
for v in ('pale', 'umbral'):
    wm = wisp.build(v)
    save(wm.img, 'soul_wisp_' + v)
    save(wm.glow, 'soul_wisp_' + v + '_glow')
for t in ('pale', 'dusk'):
    lm = minor.build_soul(t)
    save(lm.img, 'lost_soul_' + t)
    save(lm.glow, 'lost_soul_' + t + '_glow')
for method, name, m in (('soulWisp', 'soul_wisp', wisp.build()),
                        ('deathsGuard', 'deaths_guard', guard.build()),
                        ('deathReaper', 'death_reaper', death.build_reaper()),
                        ('deathBeast', 'death_beast', death.build_beast()),
                        ('lostSoul', 'lost_soul', minor.build_soul()),
                        ('soulAnchor', 'soul_anchor', minor.build_anchor()),
                        ('ferryman', 'ferryman', npcs.build('ferryman')),
                        ('gravedigger', 'gravedigger', npcs.build('gravedigger')),
                        ('prophet', 'prophet', npcs.build('prophet')),
                        ('collector', 'collector', npcs.build('collector')),
                        ('bonesmith', 'bonesmith', npcs.build('bonesmith')),
                        ('mira', 'mira', folk.build_mira()),
                        ('lamplighter', 'lamplighter', folk.build_lamplighter()),
                        ('sentry', 'sentry', folk.build_sentry()),
                        ('skeletonKid', 'skeleton_kid_0', folk.build_skelkid(0)),
                        ('lanternWisp', 'lantern_wisp', folk.build_lantern_wisp()),
                        ('hollowHunter', 'hollow_hunter', hunter.build())):
    save(m.img, name)
    save(m.glow, name + '_glow')
    models.append((method, m))
for _v in (1, 2):   # the other children: the same bones, other scarves
    save(folk.build_skelkid(_v).img, f'skeleton_kid_{_v}')
for _t in ('drowned', 'ashen', 'veiled'):   # more of the dead in the line
    _lm = minor.build_soul(_t)
    save(_lm.img, 'lost_soul_' + _t)
    save(_lm.glow, 'lost_soul_' + _t + '_glow')

save(npcs.corruption(next(m for _, m in models if m.name == 'prophet')), 'prophet_corrupt')
body = '\n\n'.join(m.java(method) for method, m in models)
with open(JAVA, 'w', newline='\n') as f:
    f.write(f"""package com.deathbound.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** GENERATED by tools/art/build.py from the same specs that paint the textures. Do not edit by hand. */
@SuppressWarnings("unused")
public final class ModelMeshes {{
	private ModelMeshes() {{}}

{body}
}}
""")
print('wrote', len(models), 'models')

# ------------------------------------------------------------------ sprites
import io
import zipfile
import numpy as np
import sprites as sp
jar = os.path.expanduser('~/.gradle/caches/fabric-loom/26.3/minecraft-client.jar')
import scythe

A = os.path.join(ROOT, 'src/main/resources/assets/deathbound')
ITEM, BLOCK, PART, GUI = (os.path.join(A, 'textures', d) for d in ('item', 'block', 'particle', 'gui'))
relic = sp.relic()
items = {'deathbound_relic': relic, 'soulbound_charm': sp.soulbound(), 'seers_charm': sp.seer(), 'wraiths_charm': sp.wraith(),
         'ferrymans_charm': sp.ferryman(), 'reapers_charm': sp.reaper(), 'soul': sp.soul(), 'heart_of_death': sp.heart(),
         'reaper_scythe': scythe.icon(), 'soul_bolt': sp.purple_vanilla(jar, 'item/fire_charge', lift=0.5, sat=1.0), 'death_orb': sp.purple_vanilla(jar, 'item/fire_charge', lift=0.5, sat=1.0),
         'gravebound_spawn_egg': sp.egg(('#1d1b22', '#2a2730', '#3a3640', '#4d4853'), ('#857a6a', '#b9ad96', '#e2d9c3'), 1),
         'soul_wisp_spawn_egg': sp.egg(('#16131c', '#24202c', '#35303e', '#47424e'), ('#4c1d7a', '#7a3cc2', '#c79bff'), 2),
         'deaths_guard_spawn_egg': sp.egg(('#17171d', '#2f2f38', '#464651', '#5c5c68'), ('#381753', '#62298d', '#9850cc'), 3),
         'death_spawn_egg': sp.egg(('#060509', '#110f16', '#1f1b27', '#2a2534'), ('#7a2fe6', '#a061ff', '#e3ccff'), 4),
         'hollow_hunter_spawn_egg': sp.egg(('#8f8778', '#b3aa98', '#d1c8b4', '#e6dfcc'), ('#3e352b', '#5f5442', '#9850cc'), 6),
         'lost_soul_spawn_egg': sp.egg(('#544184', '#6f5aa6', '#8c78c2', '#ab9ad8'), ('#cbbfeb', '#e8e1fa', '#ffffff'), 5)}
# the relic after the old King's fee: the same chain, every bit of its light gone out of it
_spent = relic.copy().astype('float32')
_lum = (_spent[..., 0] * 0.3 + _spent[..., 1] * 0.59 + _spent[..., 2] * 0.11) * 0.72
for _c, _tint in enumerate((0, 1, 6)):
    _spent[..., _c] = _lum + _tint
items['spent_chain'] = _spent.clip(0, 255).astype('uint8')
for name, img in items.items():
    sp.save(img, os.path.join(ITEM, name + '.png'))

with zipfile.ZipFile(jar) as z:
    soul_lantern = io.BytesIO(z.read('assets/minecraft/textures/block/soul_lantern.png'))
    lantern_meta = z.read('assets/minecraft/textures/block/soul_lantern.png.mcmeta')
blocks = {'soulstone': sp.soulstone(), 'soulstone_bricks': sp.bricks(), 'cracked_soulstone_bricks': sp.bricks(True),
          'chiseled_soulstone': sp.chiseled(), 'soulstone_tiles': sp.tiles(), 'soulstone_pillar': sp.pillar_side(),
          'soulstone_pillar_top': sp.pillar_top(), 'ashen_soil': sp.ashen_top(), 'ashen_soil_side': sp.ashen_side(),
          'gloom_grass': sp.gloom_grass(), 'ghostwood_log': sp.log_side(), 'ghostwood_log_top': sp.log_top(),
          'ghostwood_planks': sp.planks(), 'soul_crystal': sp.crystal(), 'soul_seal': sp.seal_frames(),
          'soul_rift': sp.rift_frames(), 'wraith_lantern': sp.lantern_from(soul_lantern)}
for name, img in blocks.items():
    sp.save(img, os.path.join(BLOCK, name + '.png'))
for name, frametime in (('soul_seal', 4), ('soul_rift', 2)):
    with open(os.path.join(BLOCK, name + '.png.mcmeta'), 'w') as f:
        f.write('{"animation": {"frametime": %d, "interpolate": true}}\n' % frametime)
with open(os.path.join(BLOCK, 'wraith_lantern.png.mcmeta'), 'wb') as f:
    f.write(lantern_meta)
for i, size in enumerate((1.2, 1.8, 2.4, 3.0)):
    sp.save(sp.mote(size), os.path.join(PART, f'soul_mote_{i}.png'))
for i in range(6):
    sp.save(sp.purple_vanilla(jar, 'particle/flame'), os.path.join(PART, f'soul_flame_{i}.png'))   # Minecraft's flame, purple
sp.save(sp.relic_gui(), os.path.join(GUI, 'relic.png'))
sp.save(sp.icon(relic), os.path.join(A, 'icon.png'))
print('wrote', len(items), 'items,', len(blocks), 'blocks, particles, gui, icon')

# ------------------------------------------------------------------ atmosphere pass (overrides the first block set)
import blocks2 as b2
veined, veined_glow = b2.veined_bricks()
chis, chis_glow = b2.chiseled()
v2 = {'soulstone': b2.soulstone(), 'soulstone_bricks': b2.soulstone_bricks(), 'cracked_soulstone_bricks': b2.cracked_bricks(),
      'chiseled_soulstone': chis, 'chiseled_soulstone_glow': chis_glow, 'soulstone_tiles': b2.tiles(),
      'soulstone_pillar': b2.pillar_side(), 'soulstone_pillar_top': b2.pillar_top(), 'polished_soulstone': b2.polished(),
      'dark_soulstone_bricks': b2.dark_bricks(), 'soul_veined_bricks': veined, 'soul_veined_bricks_glow': veined_glow,
      'remains_bone': b2.bone(), 'remains_skull': b2.skull_face(), 'remains_rag': b2.rag(), 'dark_iron': b2.iron(),
      'soul_fire': b2.soul_fire(), 'soul_embers': b2.embers(),
      'small_soul_shard': b2.shard(0), 'medium_soul_shard': b2.shard(1), 'large_soul_shard': b2.shard(2)}
for name, img in v2.items():
    sp.save(img, os.path.join(BLOCK, name + '.png'))
with open(os.path.join(BLOCK, 'soul_fire.png.mcmeta'), 'w') as f:
    f.write('{"animation": {"frametime": 2, "interpolate": true}}\n')
print('atmosphere textures:', len(v2))

# ------------------------------------------------------------------ HD pass: 32x32 lit height-field textures with variants
import hd
hd_tex = {}
for i in range(3):
    hd_tex[f'soulstone_bricks{"_" + str(i) if i else ""}'] = hd.bricks_tex(210 + i)
    hd_tex[f'soulstone{"_" + str(i) if i else ""}'] = hd.rock_tex(710 + i)
for i in range(2):
    sfx = "_" + str(i) if i else ""
    hd_tex['cracked_soulstone_bricks' + sfx] = hd.bricks_tex(220 + i, chip=0.8, cracks=3)
    hd_tex['dark_soulstone_bricks' + sfx] = hd.bricks_tex(230 + i, ramp=hd.DARK, grey_ramp=hd.DARK)
    hd_tex['soulstone_tiles' + sfx] = hd.tiles_tex(510 + i)
veined_hd, veined_hd_glow = hd.bricks_tex(31, veins=2)
chis_hd, chis_hd_glow = hd.chiseled_tex(41)
soil_top = hd.soil_top_tex(61)
hd_tex.update({'soul_veined_bricks': veined_hd, 'soul_veined_bricks_glow': veined_hd_glow, 'chiseled_soulstone': chis_hd,
               'chiseled_soulstone_glow': chis_hd_glow, 'polished_soulstone': hd.polished_tex(52), 'soulstone_pillar': hd.pillar_side_tex(53),
               'soulstone_pillar_top': hd.pillar_top_tex(54), 'ashen_soil': soil_top, 'ashen_soil_side': hd.soil_side_tex(62, soil_top),
               'ghostwood_planks': hd.planks_tex(81), 'ghostwood_log': hd.log_side_tex(82), 'ghostwood_log_top': hd.log_top_tex(83),
               'soul_seal': hd.seal_frames()})
# the ferry's timbers: the same wood, tarred black by a thousand years of the river
for _name, _src, _mul in (('ferry_planks', hd.planks_tex(91), (0.40, 0.38, 0.45)), ('ferry_dark', hd.log_side_tex(92), (0.34, 0.32, 0.38))):
    _f = _src.astype('float32')
    _f[..., :3] *= _mul
    hd_tex[_name] = _f.clip(0, 255).astype('uint8')
for name, img in hd_tex.items():
    sp.save(img, os.path.join(BLOCK, name + '.png'))
print('hd textures:', len(hd_tex))
import soulwater
sp.save(soulwater.sheet(jar), os.path.join(BLOCK, 'soulwater_still.png'))
sp.save(soulwater.sheet(jar, flow=True), os.path.join(BLOCK, 'soulwater_flow.png'))
for _n, _ft in (('soulwater_still', 3), ('soulwater_flow', 2)):
    with open(os.path.join(BLOCK, _n + '.png.mcmeta'), 'w') as f:
        f.write('{"animation": {"frametime": %d, "interpolate": true}}\n' % _ft)
sp.save(soulwater.bucket(jar), os.path.join(ITEM, 'soulwater_bucket.png'))
_fire = sp.purple_vanilla(jar, 'block/soul_fire_0')   # what the dead throw: Minecraft's fire, purple...
import colorsys as _cs
for _f in range(32):
    for _y in range(16):
        for _x in range(16):
            _p = _fire[_f * 16 + _y, _x]
            if _p[3]:   # the white-hot pixels go lilac: a white base reads as a flat cut
                _h, _s, _v = _cs.rgb_to_hsv(*(_p[:3] / 255.0))
                _r, _g, _b = _cs.hsv_to_rgb(0.77, max(_s, 0.42), _v * 0.96)
                _fire[_f * 16 + _y, _x, :3] = (int(_r * 255), int(_g * 255), int(_b * 255))
    # ...with the base rounded off (a block's fire runs flat into the block; a thrown one mustn't)
    _fire[_f * 16 + 15, :, 3] = 0
    for _y, _keep in ((14, 6), (13, 10), (12, 12), (11, 14)):
        _cut = (16 - _keep) // 2
        _fire[_f * 16 + _y, :_cut, 3] = 0
        _fire[_f * 16 + _y, 16 - _cut:, 3] = 0
    for _x in range(16):   # and its top corners, where flames would touch the frame
        if _x < 2 or _x > 13:
            _fire[_f * 16, _x, 3] = 0
sp.save(_fire, os.path.join(A, 'textures/entity/purple_fire.png'))
import deco
import icons
for _n in ('journal', 'aldous_lantern', 'miras_ribbon', 'ferrymans_oar', 'pips_ball', 'sentrys_tag', 'lantern_wisp'):
    sp.save(getattr(icons, _n)(), os.path.join(ITEM, ('underworld_journal' if _n == 'journal' else _n) + '.png'))
for _n, _img in (('dead_grass', deco.dead_grass()), ('tall_dead_grass', deco.dead_grass(True)), ('ghost_bloom', deco.ghost_bloom()),
                 ('ashen_lily', deco.ashen_lily()), ('tattered_banner', deco.tattered_banner())):
    sp.save(_img, os.path.join(BLOCK, _n + '.png'))

# ------------------------------------------------------------------ soulforging: rune item, Soul trim palette, soulforged trim pattern
import forge
sp.save(forge.rune(), os.path.join(ITEM, 'grave_rune.png'))
os.makedirs(os.path.join(A, 'textures/palettes/trim'), exist_ok=True)
sp.save(forge.palette(), os.path.join(A, 'textures/palettes/trim/soul.png'))
for layer, legs in (('humanoid', False), ('humanoid_leggings', True)):
    d = os.path.join(A, 'textures/trims/entity', layer)
    os.makedirs(d, exist_ok=True)
    sp.save(forge.pattern(legs), os.path.join(d, 'soulforged.png'))
    with open(os.path.join(d, 'soulforged.png.mcmeta'), 'w') as f:
        f.write('{"palette": {"base_palette": "trim_base"}}\n')
print('soulforge art written')
for i, img in enumerate(forge.sweep_frames()):
    sp.save(img, os.path.join(PART, f'soul_sweep_{i}.png'))
print('sweep frames written')
sp.save(forge.lantern_icon(), os.path.join(ITEM, 'wraith_lantern.png'))

sp.save(forge.open_door_charm(), os.path.join(ITEM, 'open_door_charm.png'))
sp.save(forge.tombstone_front(), os.path.join(BLOCK, 'tombstone_front.png'))
sp.save(forge.ossuary_shelf(), os.path.join(BLOCK, 'ossuary_shelf.png'))
sp.save(forge.hunters_charm(), os.path.join(ITEM, 'hunters_charm.png'))
for name, img in forge.artifacts().items():
    sp.save(img, os.path.join(ITEM, name + '.png'))
for name, img in forge.jars().items():
    sp.save(img, os.path.join(BLOCK, name + '.png'))
print('furniture art written')

# ------------------------------------------------------------------ second pass on the set dressing (relics.py)
import relics
door, door_glow = relics.carved_stone_tex()
sp.save(door, os.path.join(BLOCK, 'chiseled_soulstone.png'))
sp.save(door_glow, os.path.join(BLOCK, 'chiseled_soulstone_glow.png'))
sp.save(relics.ossified_side_tex(), os.path.join(BLOCK, 'ossified_log.png'))
sp.save(relics.ossified_top_tex(), os.path.join(BLOCK, 'ossified_log_top.png'))
shelf, shelf_glow = relics.curio_shelf_tex()
sp.save(shelf, os.path.join(BLOCK, 'curio_shelf.png'))
sp.save(shelf_glow, os.path.join(BLOCK, 'curio_shelf_glow.png'))
for group in (relics.skull_textures(), relics.arrow_parts(), relics.glowcap_textures(), relics.curio_textures()):
    for name, img in group.items():
        sp.save(img, os.path.join(BLOCK, name + '.png'))
sp.save(relics.long_bone_tex(), os.path.join(BLOCK, 'remains_bone.png'))
os.makedirs(os.path.join(A, 'textures/entity/projectiles'), exist_ok=True)
sp.save(relics.projectile_tex(), os.path.join(A, 'textures/entity/projectiles/hunter_arrow.png'))
skin, glow, crown = relics.corruption_textures()
sp.save(skin, os.path.join(A, 'textures/entity/corruption.png'))
sp.save(glow, os.path.join(A, 'textures/entity/corruption_glow.png'))
sp.save(crown, os.path.join(A, 'textures/entity/crown.png'))
shade, shade_eyes = relics.shade_tex()
sp.save(shade, os.path.join(A, 'textures/entity/shade.png'))
sp.save(shade_eyes, os.path.join(A, 'textures/entity/shade_eyes.png'))
for kind in ('kings', 'watchers', 'bell'):
    lock, lock_glow = relics.lock_tex(kind, os.path.join(BLOCK, 'dark_soulstone_bricks.png'))
    sp.save(lock, os.path.join(BLOCK, f'lock_{kind}.png'))
    sp.save(lock_glow, os.path.join(BLOCK, f'lock_{kind}_glow.png'))
    sp.save(relics.sigil_icon(kind), os.path.join(A, f'textures/item/sigil_{kind}.png'))
import zipfile
_client = zipfile.ZipFile(os.path.expanduser('~/.gradle/caches/fabric-loom/26.3/minecraft-client.jar'))
for name, img in relics.hunters_bow_textures(_client).items():
    sp.save(img, os.path.join(A, f'textures/item/{name}.png'))
print('relics written')
