#!/usr/bin/env python3
"""
Single source of truth for the Underworld character models + textures.

Each model is a tree of parts made of boxes (Minecraft "box UV" layout). This script:
  1. packs every box into a texture atlas,
  2. writes the Java LayerDefinition (src/client/java/.../geom/*Geometry.java),
  3. paints the pixel textures (base + emissive "eyes" layers),
  4. paints the item / effect icons.

Re-run after editing:  python3 tools/gen_assets.py
"""
import math
import os
import random

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "src/main/resources/assets/underworld")
GEOM_DIR = os.path.join(ROOT, "src/client/java/com/underworld/client/model/geom")


# --------------------------------------------------------------------------------------------
# Model description
# --------------------------------------------------------------------------------------------
class Cube:
    def __init__(self, origin, size, mat, inflate=0.0, mirror=False, tag=None):
        self.origin = origin
        self.size = size
        self.mat = mat
        self.inflate = inflate
        self.mirror = mirror
        self.tag = tag
        self.uv = None


class Part:
    def __init__(self, name, pivot=(0, 0, 0), rot=(0, 0, 0), cubes=(), children=()):
        self.name = name
        self.pivot = pivot
        self.rot = rot
        self.cubes = list(cubes)
        self.children = list(children)

    def walk(self):
        yield self
        for c in self.children:
            yield from c.walk()


def C(x, y, z, w, h, d, mat, inflate=0.0, mirror=False, tag=None):
    return Cube((x, y, z), (w, h, d), mat, inflate, mirror, tag)


def pack(root, tex_w, tex_h):
    cubes = [c for p in root.walk() for c in p.cubes]
    order = sorted(cubes, key=lambda c: -(c.size[1] + c.size[2]))
    x = y = row_h = 0
    for c in order:
        w, h, d = c.size
        uw, uh = 2 * (w + d), h + d
        if x + uw > tex_w:
            x, y, row_h = 0, y + row_h, 0
        c.uv = (x, y)
        x += uw
        row_h = max(row_h, uh)
    if y + row_h > tex_h:
        raise SystemExit(f"atlas overflow for {root.name}: needs {y + row_h}px of {tex_h}")


def fmt(v):
    s = f"{float(v):.4f}".rstrip("0")
    return (s + "0" if s.endswith(".") else s) + "F"


def java_geometry(root, class_name, tex_w, tex_h):
    lines = []

    def emit(part, parent_var):
        var = "p_" + part.name
        cb = "CubeListBuilder.create()"
        for c in part.cubes:
            x, y, z = c.origin
            w, h, d = c.size
            cb += f".texOffs({c.uv[0]}, {c.uv[1]})"
            if c.mirror:
                cb += ".mirror()"
            cb += f".addBox({fmt(x)}, {fmt(y)}, {fmt(z)}, {fmt(w)}, {fmt(h)}, {fmt(d)}, new CubeDeformation({fmt(c.inflate)}))"
            if c.mirror:
                cb += ".mirror(false)"
        px, py, pz = part.pivot
        rx, ry, rz = part.rot
        pose = f"PartPose.offsetAndRotation({fmt(px)}, {fmt(py)}, {fmt(pz)}, {fmt(rx)}, {fmt(ry)}, {fmt(rz)})"
        lines.append(f"\t\tPartDefinition {var} = {parent_var}.addOrReplaceChild(\"{part.name}\", {cb}, {pose});")
        for ch in part.children:
            emit(ch, var)

    emit(root, "mesh.getRoot()")
    body = "\n".join(lines)
    return f"""package com.underworld.client.model.geom;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** GENERATED by tools/gen_assets.py - edit the script, not this file. */
@SuppressWarnings("unused")
public final class {class_name} {{
	private {class_name}() {{
	}}

	public static LayerDefinition create() {{
		MeshDefinition mesh = new MeshDefinition();
{body}
		return LayerDefinition.create(mesh, {tex_w}, {tex_h});
	}}
}}
"""


# --------------------------------------------------------------------------------------------
# Painting helpers
# --------------------------------------------------------------------------------------------
def faces(c):
    """Box-UV face rectangles: name -> (x, y, w, h)."""
    u, v = c.uv
    w, h, d = c.size
    return {
        "up": (u + d, v, w, d),
        "down": (u + d + w, v, w, d),
        "east": (u, v + d, d, h),
        "north": (u + d, v + d, w, h),  # model front (-Z)
        "west": (u + d + w, v + d, d, h),
        "south": (u + 2 * d + w, v + d, w, h),
    }


def shade(rgb, f):
    return tuple(max(0, min(255, int(round(ch * f)))) for ch in rgb)


def pick(rng, palette):
    return palette[rng.randrange(len(palette))]


TRANSPARENT = (0, 0, 0, 0)


class Painter:
    def __init__(self, img, glow, seed):
        self.img = img
        self.glow = glow  # dict phase -> Image (emissive layers) or None
        self.rng = random.Random(seed)

    def px(self, x, y, rgb, a=255):
        if 0 <= x < self.img.width and 0 <= y < self.img.height:
            self.img.putpixel((x, y), (*rgb, a) if len(rgb) == 3 else rgb)

    def gpx(self, x, y, rgb, phases=(1, 2, 3), a=255):
        if self.glow is None:
            return
        for p in phases:
            g = self.glow[p]
            if 0 <= x < g.width and 0 <= y < g.height:
                g.putpixel((x, y), (*rgb, a))

    def fill(self, rect, palette, face=None, vertical_streak=False):
        x0, y0, w, h = rect
        for yy in range(h):
            for xx in range(w):
                col = pick(self.rng, palette)
                if vertical_streak and (xx % 3 == 0):
                    col = shade(col, 0.82)
                self.px(x0 + xx, y0 + yy, col)


# palettes -----------------------------------------------------------------------------------
BONE = [(150, 145, 138), (138, 133, 127), (160, 155, 147), (128, 123, 118), (145, 140, 133)]
BONE_DARK = [(104, 99, 95), (94, 90, 86), (112, 107, 102), (98, 94, 90)]
CLOTH = [(34, 30, 40), (39, 34, 46), (30, 27, 35), (43, 38, 51), (36, 32, 43)]
CLOTH_EDGE = [(54, 47, 64), (60, 52, 71)]
VOID = [(7, 5, 10), (9, 7, 12), (6, 4, 9)]
LEATHER = [(98, 73, 53), (86, 64, 47), (108, 81, 59), (78, 58, 42)]
METAL = [(104, 106, 114), (92, 94, 102), (118, 120, 128), (84, 86, 94)]
WOOD = [(96, 70, 47), (84, 60, 40), (106, 78, 52), (74, 53, 36), (90, 65, 44)]
WOOD_DARK = [(58, 42, 30), (50, 36, 26), (66, 48, 34)]
STRING = [(150, 146, 156), (138, 134, 145)]
SPECTRAL = [(118, 52, 182), (132, 62, 200), (106, 44, 166)]
SPECTRAL_GLOW = (120, 40, 210)
SPECTRAL_HOT = (160, 80, 240)
EYE_CORE = (245, 205, 255)
EYE_GLOW = (190, 80, 255)
SOUL = [(140, 70, 210), (160, 90, 230), (120, 55, 190)]

ROBE = [(74, 64, 56), (66, 57, 50), (82, 71, 61), (60, 52, 46), (70, 61, 53)]
ROBE_DARK = [(46, 40, 36), (40, 35, 32), (52, 45, 40)]
TROUSER = [(42, 37, 34), (36, 32, 30), (48, 42, 38)]
BOOT = [(34, 27, 22), (28, 22, 18)]
SATCHEL = [(60, 56, 62), (52, 48, 54), (68, 63, 70)]
SATCHEL_TRIM = [(84, 62, 120), (74, 54, 108)]
PARCHMENT = [(206, 190, 150), (192, 176, 136), (214, 200, 160)]
SKULL = [(206, 202, 190), (192, 188, 176), (214, 210, 198)]
KEY = [(120, 104, 70), (138, 118, 78)]
SKIN_SHADOW = [(14, 12, 16), (18, 15, 20)]
GLOVE = [(52, 40, 32), (46, 35, 28)]


def paint_cube(p, c):
    f = faces(c)
    m = c.mat
    tag = c.tag or ""

    if m == "bone":
        for name, r in f.items():
            p.fill(r, BONE)
            x0, y0, w, h = r
            # darker joint bands at both ends of long bones
            if name in ("north", "south", "east", "west") and h >= 6:
                for xx in range(w):
                    p.px(x0 + xx, y0, pick(p.rng, BONE_DARK))
                    p.px(x0 + xx, y0 + h - 1, pick(p.rng, BONE_DARK))
    elif m == "bone_dark":
        for r in f.values():
            p.fill(r, BONE_DARK)
    elif m == "ribs":
        for name, r in f.items():
            x0, y0, w, h = r
            for yy in range(h):
                for xx in range(w):
                    rib_row = yy % 2 == 0
                    sternum = name == "north" and xx in (w // 2,)
                    spine = name == "south" and xx in (w // 2,)
                    edge = name in ("up", "down") and (xx in (0, w - 1) or yy in (0, h - 1))
                    if name in ("up", "down"):
                        p.px(x0 + xx, y0 + yy, pick(p.rng, BONE) if edge else TRANSPARENT)
                    elif rib_row or sternum or spine:
                        p.px(x0 + xx, y0 + yy, pick(p.rng, BONE if rib_row else BONE_DARK))
                    else:
                        p.px(x0 + xx, y0 + yy, TRANSPARENT)
    elif m in ("cloth", "cloth_tattered"):
        for name, r in f.items():
            p.fill(r, CLOTH)
            x0, y0, w, h = r
            if m == "cloth_tattered" and name in ("north", "south", "east", "west"):
                # ragged hem: random-depth transparent notches at the bottom, a few moth holes
                for xx in range(w):
                    depth = p.rng.choice([0, 1, 1, 2, 3, 4, 5, 6]) if h > 12 else p.rng.choice([0, 1, 2])
                    for k in range(depth):
                        p.px(x0 + xx, y0 + h - 1 - k, TRANSPARENT)
                for _ in range(max(1, (w * h) // 140)):
                    hx, hy = x0 + p.rng.randrange(w), y0 + p.rng.randrange(max(1, h - 6))
                    p.px(hx, hy, TRANSPARENT)
                for yy in range(0, h, 7):  # faint fold lines
                    for xx in range(w):
                        if p.rng.random() < 0.5:
                            p.px(x0 + xx, y0 + yy, pick(p.rng, CLOTH_EDGE))
    elif m == "hood":
        for name, r in f.items():
            x0, y0, w, h = r
            if name == "north":
                # black void inside the hood, 1px cloth rim, a single eye
                for yy in range(h):
                    for xx in range(w):
                        rim = xx in (0, w - 1) or yy == 0 or (yy == 1 and xx in (1, w - 2))
                        p.px(x0 + xx, y0 + yy, pick(p.rng, CLOTH_EDGE if rim else VOID))
                ex, ey = x0 + w // 2 + 1, y0 + h // 2
                p.px(ex, ey, (150, 70, 210))
                p.gpx(ex, ey, EYE_CORE)
                # glow halo grows with the phase
                for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                    p.gpx(ex + dx, ey + dy, EYE_GLOW, phases=(2, 3), a=170)
                for dx, dy in ((-1, -1), (1, -1), (-1, 1), (1, 1), (-2, 0), (2, 0)):
                    p.gpx(ex + dx, ey + dy, EYE_GLOW, phases=(3,), a=110)
            else:
                p.fill(r, CLOTH)
                if name in ("east", "west", "south"):
                    for xx in range(w):
                        p.px(x0 + xx, y0 + h - 1, pick(p.rng, CLOTH_EDGE))
    elif m == "leather":
        for name, r in f.items():
            p.fill(r, LEATHER)
            x0, y0, w, h = r
            for yy in range(1, h, 3):  # straps / stitching
                for xx in range(w):
                    p.px(x0 + xx, y0 + yy, shade(pick(p.rng, LEATHER), 0.7))
    elif m == "metal":
        for name, r in f.items():
            p.fill(r, METAL)
            x0, y0, w, h = r
            if w > 1 and h > 1:
                p.px(x0 + 1, y0 + 1, (110, 112, 118))
    elif m == "bracer":
        for name, r in f.items():
            p.fill(r, LEATHER)
            x0, y0, w, h = r
            for xx in range(w):
                p.px(x0 + xx, y0, pick(p.rng, METAL))
                p.px(x0 + xx, y0 + h - 1, pick(p.rng, METAL))
            if h > 4 and w > 1:
                p.px(x0 + w // 2, y0 + h // 2, (104, 106, 112))
    elif m in ("wood", "wood_rune"):
        for name, r in f.items():
            p.fill(r, WOOD, vertical_streak=True)
            x0, y0, w, h = r
            for _ in range(max(1, w * h // 6)):
                p.px(x0 + p.rng.randrange(w), y0 + p.rng.randrange(h), pick(p.rng, WOOD_DARK))
            if m == "wood_rune" and name in ("north", "south", "east", "west") and h >= 3:
                ry = y0 + h // 2
                p.px(x0 + w // 2, ry, (96, 40, 140))
                p.gpx(x0 + w // 2, ry, SPECTRAL_GLOW, phases=(2, 3), a=200)
    elif m == "wood_dark":
        for r in f.values():
            p.fill(r, WOOD_DARK)
    elif m == "string":
        for r in f.values():
            p.fill(r, STRING)
    elif m == "spectral":
        for name, r in f.items():
            x0, y0, w, h = r
            for yy in range(h):
                for xx in range(w):
                    p.px(x0 + xx, y0 + yy, pick(p.rng, SPECTRAL))
                    p.gpx(x0 + xx, y0 + yy, SPECTRAL_HOT if (xx + yy) % 3 == 0 else SPECTRAL_GLOW)
    elif m == "soul":
        for name, r in f.items():
            x0, y0, w, h = r
            for yy in range(h):
                for xx in range(w):
                    p.px(x0 + xx, y0 + yy, pick(p.rng, SOUL))
                    p.gpx(x0 + xx, y0 + yy, SPECTRAL_HOT if p.rng.random() < 0.3 else SPECTRAL_GLOW, phases=(2, 3))
    # ---------------- Collector materials ----------------
    elif m in ("robe", "robe_tattered"):
        for name, r in f.items():
            p.fill(r, ROBE)
            x0, y0, w, h = r
            for _ in range(max(1, w * h // 10)):  # wear, dust, patches
                p.px(x0 + p.rng.randrange(w), y0 + p.rng.randrange(h), pick(p.rng, ROBE_DARK))
            if m == "robe_tattered" and name in ("north", "south", "east", "west"):
                for xx in range(w):
                    for k in range(p.rng.choice([0, 0, 1, 1, 2])):
                        p.px(x0 + xx, y0 + h - 1 - k, TRANSPARENT)
            if tag == "torso" and name == "north":
                for yy in range(h):  # robe opening seam
                    p.px(x0 + w // 2, y0 + yy, pick(p.rng, ROBE_DARK))
    elif m == "robe_dark":
        for r in f.values():
            p.fill(r, ROBE_DARK)
    elif m == "chood":
        for name, r in f.items():
            x0, y0, w, h = r
            if name == "north":
                for yy in range(h):
                    for xx in range(w):
                        rim = xx in (0, w - 1) or yy in (0,)
                        p.px(x0 + xx, y0 + yy, pick(p.rng, ROBE if rim else ROBE_DARK) if rim else TRANSPARENT)
            else:
                p.fill(r, ROBE)
                for _ in range(max(1, w * h // 9)):
                    p.px(x0 + p.rng.randrange(w), y0 + p.rng.randrange(h), pick(p.rng, ROBE_DARK))
    elif m == "cface":
        for name, r in f.items():
            x0, y0, w, h = r
            p.fill(r, SKIN_SHADOW)
            if name == "north":
                ey = y0 + h // 2 - 1
                for ex in (x0 + 2, x0 + w - 3):
                    p.px(ex, ey, (112, 60, 160))
                    p.gpx(ex, ey, (170, 100, 230), phases=(1,), a=150)
    elif m == "trouser":
        for name, r in f.items():
            p.fill(r, TROUSER)
            x0, y0, w, h = r
            if name in ("north", "south", "east", "west"):
                for yy in range(max(0, h - 3), h):
                    for xx in range(w):
                        p.px(x0 + xx, y0 + yy, pick(p.rng, BOOT))
    elif m == "glove":
        for r in f.values():
            p.fill(r, GLOVE)
    elif m == "belt":
        for name, r in f.items():
            p.fill(r, LEATHER)
            x0, y0, w, h = r
            if name == "north":
                p.px(x0 + w // 2, y0 + h // 2, (150, 130, 80))
                p.px(x0 + w // 2 - 1, y0 + h // 2, (150, 130, 80))
    elif m == "satchel":
        for name, r in f.items():
            p.fill(r, SATCHEL)
            x0, y0, w, h = r
            for xx in range(w):
                p.px(x0 + xx, y0, pick(p.rng, SATCHEL_TRIM))
            if name == "north" and h >= 3:
                for xx in range(w):
                    p.px(x0 + xx, y0 + 1, shade(SATCHEL[0], 0.7))
                p.px(x0 + w // 2, y0 + 2, (150, 130, 80))
    elif m == "skull":
        for name, r in f.items():
            p.fill(r, SKULL)
            x0, y0, w, h = r
            if name == "north" and w >= 2:
                p.px(x0, y0, (30, 28, 26))
                p.px(x0 + w - 1, y0, (30, 28, 26))
    elif m == "parchment":
        for name, r in f.items():
            p.fill(r, PARCHMENT)
            x0, y0, w, h = r
            if h > 1:
                p.px(x0, y0 + h // 2, (120, 40, 40))
    elif m == "key":
        for r in f.values():
            p.fill(r, KEY)
    elif m == "crystal":
        for name, r in f.items():
            x0, y0, w, h = r
            for yy in range(h):
                for xx in range(w):
                    p.px(x0 + xx, y0 + yy, (150, 90, 210))
                    p.gpx(x0 + xx, y0 + yy, (200, 140, 255), phases=(1,), a=200)
    else:
        raise SystemExit("unknown material " + m)


def render_model(root, tex_w, tex_h, out_base, glow_names, seed):
    img = Image.new("RGBA", (tex_w, tex_h), TRANSPARENT)
    glow = {p: Image.new("RGBA", (tex_w, tex_h), TRANSPARENT) for p in (1, 2, 3)}
    painter = Painter(img, glow, seed)
    for part in root.walk():
        for c in part.cubes:
            paint_cube(painter, c)
    os.makedirs(os.path.dirname(out_base), exist_ok=True)
    img.save(out_base + ".png")
    for phase, name in glow_names.items():
        glow[phase].save(os.path.join(os.path.dirname(out_base), name + ".png"))


# --------------------------------------------------------------------------------------------
# THE HOLLOW HUNTER  (ground is y = 24, front is -Z, ~54px / 3.4 blocks tall before hunching)
# --------------------------------------------------------------------------------------------
def spectral_arrow(name, pivot, rot):
    return Part(name, pivot, rot, [
        C(-0.5, -12, -0.5, 1, 12, 1, "spectral"),     # shaft
        C(-1, -15, -1, 2, 3, 2, "spectral", inflate=-0.15),  # head
        C(-1.5, -1, -0.5, 3, 3, 1, "spectral", inflate=-0.1),  # fletching
    ])


def hunter_model():
    halo = []
    # fan of floating spectral arrows rising from behind the LEFT shoulder, splayed outward (reference image)
    for i in range(7):
        pivot = (2.5 + i * 1.1, -1.0 - i * 0.35, 0.8 + (i % 2) * 0.9)
        halo.append(spectral_arrow(f"spectral_{i}", pivot, (0.12 + (i % 3) * 0.05, 0, 0.10 + i * 0.19)))

    bow = Part("bow", (0, 15.5, 0), (0, 0, 0), [
        C(-1, -3, -1, 2, 6, 2, "leather", inflate=0.05),           # grip wrap
        C(-0.5, -8, -0.5, 1, 5, 1, "wood_rune", inflate=0.15),     # upper limb
        C(-0.5, -12, 0.5, 1, 4, 1, "wood", inflate=0.1),
        C(-0.5, -15, 1.5, 1, 3, 1, "wood"),
        C(-0.5, -17, 2.5, 1, 2, 1, "wood_dark"),                     # upper tip
        C(-1, -9, -1, 2, 1, 1, "wood_dark"),                          # gnarl
        C(-0.5, 3, -0.5, 1, 5, 1, "wood_rune", inflate=0.15),      # lower limb
        C(-0.5, 8, 0.5, 1, 4, 1, "wood", inflate=0.1),
        C(-0.5, 12, 1.5, 1, 3, 1, "wood"),
        C(-0.5, 15, 2.5, 1, 2, 1, "wood_dark"),                      # lower tip
        C(0, 10, 0, 1, 1, 2, "wood_dark"),                            # gnarl
    ], [
        # string in two halves so it can bend back to the drawing hand
        Part("string_top", (0, -16, 3.0), (0, 0, 0), [C(-0.5, 0, -0.5, 1, 16, 1, "string", inflate=-0.4)]),
        Part("string_bottom", (0, 16, 3.0), (0, 0, 0), [C(-0.5, -16, -0.5, 1, 16, 1, "string", inflate=-0.4)]),
        Part("nocked_arrow", (0, 0, 3.0), (0, 0, 0), [
            C(-0.5, -0.5, -21, 1, 1, 21, "spectral", inflate=-0.1),
            C(-1, -1, -24, 2, 2, 3, "spectral", inflate=-0.15),
            C(-1.5, -0.5, -1, 3, 1, 3, "spectral", inflate=-0.1),
        ]),
    ])

    def arm(side):
        s = -1 if side == "right" else 1
        children = [Part(f"{side}_forearm", (0, 15, 0), (0, 0, 0), [
            C(-1, 0, -1, 2, 14, 2, "bone"),
            C(-1.5, 3, -1.5, 3, 7, 3, "bracer"),
            C(-1.5, 14, -1.5, 3, 3, 3, "bone_dark"),               # hand
            C(-1.5, 17, -1.5, 1, 4, 1, "bone"),                     # long fingers
            C(-0.5 + 0.5 * s, 17, -1.5, 1, 5, 1, "bone"),
            C(0.5, 17, 0.5, 1, 3, 1, "bone"),
        ], [bow] if side == "right" else [Part("hand_arrow", (0, 16, 0), (0, 0, 0), [
            C(-0.5, -8, -0.5, 1, 22, 1, "spectral", inflate=-0.1),
            C(-1, 14, -1, 2, 3, 2, "spectral", inflate=-0.15),
            C(-1.5, -9, -0.5, 3, 3, 1, "spectral", inflate=-0.1),
        ])])]
        return Part(f"{side}_arm", (7 * s, -21.5, 0), (0, 0, 0.06 * -s), [
            C(-2, -2, -2, 4, 4, 4, "leather", inflate=0.1),          # pauldron
            C(-1, 1, -1, 2, 15, 2, "bone_dark"),                     # upper arm
            C(-1.5, 6, -1.5, 3, 3, 3, "bracer") if side == "left" else C(-1.5, 8, -1.5, 3, 2, 3, "leather"),
        ], children)

    def leg(side):
        s = -1 if side == "right" else 1
        return Part(f"{side}_leg", (2.5 * s, 0, 0), (0, 0, 0), [
            C(-1, 0, -1, 2, 12, 2, "bone"),
            C(-1.5, 11, -1.5, 3, 2, 3, "bone_dark"),                 # knee
        ], [Part(f"{side}_shin", (0, 12, 0), (0, 0, 0), [
            C(-1, 0, -1, 2, 10, 2, "bone"),
            C(-1.5, 10, -4, 3, 2, 5, "bone_dark"),                   # foot
        ])])

    torso = Part("torso", (0, 0, 0), (0, 0, 0), [
        C(-1, -22, -0.5, 2, 22, 2, "bone_dark"),                     # spine
        C(-4.5, -21, -3, 9, 10, 5, "ribs"),                          # hollow rib cage
        C(-7, -23.5, -1.5, 14, 2, 3, "bone"),                        # shoulder girdle
        C(-5.5, -25, -3.5, 11, 3, 7, "cloth"),                       # mantle
        C(-3.5, -3, -2, 7, 3, 4, "bone_dark"),                       # pelvis
    ], [
        Part("soul_core", (0, -16, -0.5), (0, 0, 0), [C(-1.5, -1.5, -1.5, 3, 3, 3, "soul")]),
        Part("head", (0, -24.5, -0.5), (0, 0, 0), [
            C(-4.5, -10, -5, 9, 10, 9, "hood"),
            C(-3.5, -11, -3.5, 7, 1, 7, "cloth"),                    # hood crown
            C(-4, -3, 3.5, 8, 5, 2, "cloth_tattered"),               # hood drape at the back
        ]),
        Part("cloak", (0, -24, 3.2), (0, 0, 0), [
            C(-7.5, 0, 0, 15, 39, 1, "cloth_tattered"),
        ], [
            Part("cloak_left", (7.5, 0, 0), (0, -0.2, 0), [C(0, 0, -7, 1, 35, 8, "cloth_tattered")]),
            Part("cloak_right", (-7.5, 0, 0), (0, 0.2, 0), [C(-1, 0, -7, 1, 35, 8, "cloth_tattered")]),
        ]),
        Part("quiver", (-2.5, -20, 4.6), (0.1, 0, 0.5), [
            C(-2, -2, 0, 4, 13, 3, "leather"),
            C(-1.5, -6, 0.5, 1, 4, 1, "spectral"),
            C(0, -7, 1, 1, 5, 1, "spectral"),
            C(1, -5, 1.5, 1, 3, 1, "spectral"),
        ]),
        Part("halo", (0, -20, 5), (0, 0, 0), [], halo),
        arm("right"),
        arm("left"),
    ])

    return Part("root", (0, 0, 0), (0, 0, 0), [], [
        torso,
        leg("right"),
        leg("left"),
    ])


# --------------------------------------------------------------------------------------------
# THE COLLECTOR  (hunched, hooded, ~1.9 blocks)
# --------------------------------------------------------------------------------------------
def collector_model():
    def arm(side):
        s = -1 if side == "right" else 1
        return Part(f"{side}_arm", (5 * s, -10.5, 0), (0, 0, 0), [
            C(-2, -1, -2, 4, 11, 4, "robe"),
            C(-2.5, 7, -2.5, 5, 3, 5, "robe_tattered"),               # wide cuff
            C(-1.5, 10, -1.5, 3, 2, 3, "glove"),
        ])

    def leg(side):
        s = -1 if side == "right" else 1
        return Part(f"{side}_leg", (2 * s, 12, 0), (0, 0, 0), [C(-2, 0, -2, 4, 12, 4, "trouser")])

    body = Part("body", (0, 12, 0), (0, 0, 0), [
        C(-4, -12, -2.5, 8, 12, 5, "robe", tag="torso"),
        C(-5, -12.5, -3.5, 10, 4, 7, "robe_tattered"),                 # shoulder mantle
        C(-4.5, -2, -3, 9, 2, 6, "belt"),
    ], [
        Part("skirt", (0, 0, 0), (0, 0, 0), [C(-4.5, 0, -3, 9, 9, 6, "robe_tattered")]),
        Part("satchel", (3.5, -1, -2.5), (0, -0.25, 0), [
            C(-1, 0, -2, 5, 5, 3, "satchel"),
            C(0, -1, -1.5, 3, 1, 2, "satchel"),
        ], [Part("satchel_crystal", (2.5, -1, -1), (0, 0, 0.3), [C(-0.5, -2, -0.5, 1, 2, 1, "crystal")])]),
        Part("belt_skull", (-2, 0, -3.3), (0, 0, 0.1), [C(-1, 0, -1, 2, 2, 2, "skull")]),
        Part("belt_scroll", (0.5, 0, -3.3), (0, 0, -0.15), [C(-0.5, 0, -0.5, 1, 4, 1, "parchment")]),
        Part("belt_key", (-3.6, 0, -3.2), (0, 0, 0.1), [C(-0.5, 0, -0.5, 1, 3, 1, "key", inflate=-0.2)]),
        Part("head", (0, -12, -1), (0, 0, 0), [
            C(-3.5, -7.5, -3, 7, 7, 7, "cface"),
            C(-4.5, -9, -4.5, 9, 9, 9, "chood"),
            C(-2.5, -10, -2, 5, 1, 6, "robe"),                        # hood peak
            C(-3.5, -6, 4.5, 7, 6, 2, "robe_tattered"),               # hood back drape
        ]),
        arm("right"),
        arm("left"),
    ])
    return Part("root", (0, 0, 0), (0, 0, 0), [], [body, leg("right"), leg("left")])


# --------------------------------------------------------------------------------------------
# Spectral bolt (the floating summoned arrows)  - points along -Z
# --------------------------------------------------------------------------------------------
def bolt_model():
    return Part("root", (0, 0, 0), (0, 0, 0), [
        C(-0.5, -0.5, -7, 1, 1, 14, "spectral"),
        C(-1.5, -1.5, -10, 3, 3, 3, "spectral", inflate=-0.5),
        C(-2, -0.5, 4, 4, 1, 3, "spectral", inflate=-0.1),
        C(-0.5, -2, 4, 1, 4, 3, "spectral", inflate=-0.1),
    ])


# --------------------------------------------------------------------------------------------
# 16x16 item art
# --------------------------------------------------------------------------------------------
def sprite(rows, palette):
    img = Image.new("RGBA", (16, 16), TRANSPARENT)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != "." and ch in palette:
                col = palette[ch]
                img.putpixel((x, y), (*col, 255) if len(col) == 3 else col)
    return img


ITEM_PAL = {
    "w": (74, 55, 38), "W": (52, 38, 27), "d": (36, 26, 19), "l": (96, 70, 48),
    "g": (60, 46, 36), "s": (150, 146, 156), "p": (140, 70, 210), "P": (205, 130, 255),
    "v": (96, 40, 140), "k": (20, 16, 26), "b": (92, 88, 84), "B": (60, 57, 55), "m": (90, 92, 98),
    "y": (206, 190, 150), "Y": (176, 158, 118), "o": (160, 128, 70), "O": (120, 92, 50),
    "r": (130, 40, 40), "c": (200, 200, 190), "C": (150, 146, 136), "a": (230, 200, 255),
    "e": (70, 62, 80), "E": (44, 38, 52), "h": (210, 170, 90), "H": (150, 110, 50), "x": (180, 60, 70),
}

ITEMS = {
    # bow with a bowed, gnarled stave; purple runes; string on the left
    "hollow_bow": [
        "..........Wwd...",
        "........WwP.s...",
        ".......Ww...s...",
        "......wv...s....",
        ".....Ww....s....",
        "....wW....s.....",
        "...Wgg...s......",
        "...ggW..s.......",
        "...lW..s........",
        "..vw...s........",
        "..Ww..s.........",
        ".Ww..s..........",
        ".w..s...........",
        "dWPs............",
        "..s.............",
        "................",
    ],
    "hollow_arrow": [
        "................",
        "............aP..",
        "...........aPPP.",
        "............PPp.",
        "...........ddp..",
        "..........dd....",
        ".........dd.....",
        "........dd......",
        ".......dd.......",
        "......dd........",
        ".v...dd.........",
        ".pv.dd..........",
        "..pdd...........",
        "..pvp...........",
        ".p..v...........",
        "................",
    ],
    "hunters_eye": [
        "................",
        "................",
        "................",
        ".....kkkkkk.....",
        "...kkEeeeeEkk...",
        "..kEevvvvvveEk..",
        ".kEvvppPPppvvEk.",
        ".kevpPaaaaPpvek.",
        ".kevpPaaaaPpvek.",
        ".kEvvppPPppvvEk.",
        "..kEevvvvvveEk..",
        "...kkEeeeeEkk...",
        ".....kkkkkk.....",
        "................",
        "................",
        "................",
    ],
    "broken_soul_lantern": [
        "................",
        ".......kk.......",
        "......k..k......",
        ".....mmmmmm.....",
        "....mkkkkkkm....",
        "....mk.pa.km....",
        "....m.pPPp.m....",
        "....mkPaaPkm....",
        "....m.pPPp..m...",
        "....mk.pp.k.....",
        "....mkkkkkkm....",
        ".....mmmm.m.....",
        "................",
        "................",
        "................",
        "................",
    ],
    "ancient_death_coin": [
        "................",
        "................",
        "......HHHH......",
        "....HHhhhhHH....",
        "...HhhOOOOhhH...",
        "...HhOhkkhOhH...",
        "..HhhOkbbkOhhH..",
        "..HhhOkbbkOhhH..",
        "..HhhOhkkhOhhH..",
        "..HhhOhkkhOhhH..",
        "...HhOOkkOOhH...",
        "...HhhOOOOhhH...",
        "....HHhhhhHH....",
        "......HHHH......",
        "................",
        "................",
    ],
    "wardens_seal": [
        "................",
        "......eeee......",
        "....eeEEEEee....",
        "...eEEcccEEEe...",
        "..eEEcEEEcEEEe..",
        "..eEcEEaaEEcEe..",
        ".eEEcEaPPaEc.e..",
        ".eEEcEaPPaEc....",
        ".eEEEcEaaEc.....",
        "..eEEEcEEc..e...",
        "..eEEEEccE.Ee...",
        "...eEEEEEEEe....",
        "....eeEEEe......",
        "......ee........",
        "................",
        "................",
    ],
    "hollow_crystal": [
        "................",
        ".......a........",
        "......aPp.......",
        "......Ppv.......",
        ".....aPpvv......",
        ".....Pp.pv......",
        "....aP...v......",
        "....Pp...pv.....",
        "....Pp...pv.....",
        "....pv..pvv.....",
        ".....pv.vv......",
        ".....vpvv.......",
        "......vv........",
        "................",
        "................",
        "................",
    ],
    "forgotten_crown": [
        "................",
        "................",
        "................",
        "..h....h....h...",
        "..hh..hxh..hh...",
        "..hHh.hHh.h.h...",
        "..hHHhhHhhH.h...",
        "..hHHHHHHHH.....",
        "..hxHHpHHxH.hh..",
        "..hHHHHHHHHHHh..",
        "..HHHHHHHHHHHH..",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "sealed_relic": [
        "................",
        "......kkkk......",
        ".....kmmmmk.....",
        "....kmkkkkmk....",
        "....kmkPPkmk....",
        "....kmkaakmk....",
        "....kmkPPkmk....",
        "....kmkkkkmk....",
        "....kmmrrmmk....",
        "....kmrrrrmk....",
        "....kmmrrmmk....",
        "....kmmmmmmk....",
        ".....kkkkkk.....",
        "................",
        "................",
        "................",
    ],
    "collector_ledger": [
        "................",
        "..EEEEEEEEEEE...",
        "..EyyyyyyyyyEe..",
        "..EyYYYyYYYyEe..",
        "..EyyyyyyyyyEe..",
        "..EyYYyYYYyyEe..",
        "..EyyyyyyyyyEe..",
        "..EyYYYYyYYyEe..",
        "..EyyyypyyyyEe..",
        "..EyyyPaPyyyEe..",
        "..EyyyypyyyyEe..",
        "..EyyyyyyyyyEe..",
        "..EEEEEEEEEEEe..",
        "...eeeeeeeeeee..",
        "................",
        "................",
    ],
}


def bow_pulling(base_rows, pull):
    """Pull the string back (to the right) by shifting string pixels."""
    rows = [list(r) for r in base_rows]
    for y in range(16):
        for x in range(16):
            if rows[y][x] == "s":
                rows[y][x] = "."
    # string from top tip (13,0)->(3,13) bent toward the nock point
    top, bottom = (12, 1), (2, 14)
    mid = (7 + pull, 7 + pull)
    for (a, b) in ((top, mid), (mid, bottom)):
        steps = max(abs(b[0] - a[0]), abs(b[1] - a[1]))
        for i in range(steps + 1):
            x = round(a[0] + (b[0] - a[0]) * i / steps)
            y = round(a[1] + (b[1] - a[1]) * i / steps)
            if rows[y][x] == ".":
                rows[y][x] = "s"
    # nocked hollow arrow pointing toward the upper right
    ax, ay = mid
    for i in range(1, 6 + pull):
        x, y = ax - i, ay - i
        if 0 <= x < 16 and 0 <= y < 16 and rows[y][x] in ".s":
            rows[y][x] = "d"
    hx, hy = ax - 6 - pull, ay - 6 - pull
    for dx, dy, ch in ((0, 0, "P"), (-1, 0, "p"), (0, -1, "p"), (-1, -1, "a")):
        x, y = hx + dx, hy + dy
        if 0 <= x < 16 and 0 <= y < 16:
            rows[y][x] = ch
    return ["".join(r) for r in rows]


def effect_icon():
    img = Image.new("RGBA", (18, 18), TRANSPARENT)
    cx, cy = 8.5, 8.5
    for y in range(18):
        for x in range(18):
            d = math.hypot(x - cx, y - cy)
            if 6.0 <= d < 7.6:
                img.putpixel((x, y), (120, 50, 190, 255))
            elif 5.0 <= d < 6.0:
                img.putpixel((x, y), (60, 20, 100, 255))
    for (x, y) in ((8, 4), (9, 4), (8, 5), (9, 5), (8, 6), (9, 6), (8, 7), (9, 7), (8, 8), (9, 8),
                   (8, 11), (9, 11), (8, 12), (9, 12)):
        img.putpixel((x, y), (225, 170, 255, 255))
    for (x, y) in ((7, 9), (10, 9), (7, 10), (10, 10)):
        img.putpixel((x, y), (160, 80, 230, 255))
    return img


def spawn_egg(base, spots):
    img = Image.new("RGBA", (16, 16), TRANSPARENT)
    rng = random.Random(hash(base))
    for y in range(16):
        for x in range(16):
            dx, dy = (x - 7.5) / 5.6, (y - 8.6) / 7.0
            if dx * dx + dy * dy <= 1.0:
                col = base if rng.random() > 0.25 else spots
                if y < 6 and dx < -0.2:
                    col = shade(col, 1.25)
                img.putpixel((x, y), (*col, 255))
    return img


def arrow_entity_texture(core, fletch, head):
    """Vanilla-layout 32x32 arrow texture (side planes at y 0-4, back cross at y 5-9)."""
    img = Image.new("RGBA", (32, 32), TRANSPARENT)
    for x in range(16):
        img.putpixel((x, 2), (*core, 255))
    for x in range(0, 4):
        for y in (1, 3):
            img.putpixel((x, y), (*head, 255))
    img.putpixel((0, 2), (*head, 255))
    for x in range(11, 16):
        for y in (0, 1, 3, 4):
            if (x + y) % 2 == 0 or y in (1, 3):
                img.putpixel((x, y), (*fletch, 255))
    for x in range(5):
        for y in range(5, 10):
            if x == 2 or y == 7:
                img.putpixel((x, y), (*fletch, 255))
    return img


# --------------------------------------------------------------------------------------------
def main():
    hunter = hunter_model()
    pack(hunter, 128, 128)
    collector = collector_model()
    pack(collector, 128, 64)
    bolt = bolt_model()
    pack(bolt, 64, 32)

    os.makedirs(GEOM_DIR, exist_ok=True)
    for model, cls, w, h in ((hunter, "HollowHunterGeometry", 128, 128),
                             (collector, "CollectorGeometry", 128, 64),
                             (bolt, "SpectralBoltGeometry", 64, 32)):
        with open(os.path.join(GEOM_DIR, cls + ".java"), "w") as fh:
            fh.write(java_geometry(model, cls, w, h))

    ent = os.path.join(ASSETS, "textures/entity")
    render_model(hunter, 128, 128, os.path.join(ent, "hollow_hunter/hollow_hunter"),
                 {1: "hollow_hunter_glow_1", 2: "hollow_hunter_glow_2", 3: "hollow_hunter_glow_3"}, 7)
    render_model(collector, 128, 64, os.path.join(ent, "collector/collector"), {1: "collector_glow"}, 11)
    render_model(bolt, 64, 32, os.path.join(ent, "spectral_bolt/spectral_bolt"), {1: "spectral_bolt_glow"}, 3)

    proj = os.path.join(ent, "projectiles")
    os.makedirs(proj, exist_ok=True)
    arrow_entity_texture((48, 36, 28), (140, 70, 210), (200, 130, 255)).save(os.path.join(proj, "hollow_arrow.png"))
    arrow_entity_texture((60, 46, 34), (90, 60, 120), (150, 150, 160)).save(os.path.join(proj, "hollow_shot.png"))

    items = os.path.join(ASSETS, "textures/item")
    os.makedirs(items, exist_ok=True)
    for name, rows in ITEMS.items():
        sprite(rows, ITEM_PAL).save(os.path.join(items, name + ".png"))
    for i, pull in enumerate((1, 2, 3)):
        sprite(bow_pulling(ITEMS["hollow_bow"], pull), ITEM_PAL).save(os.path.join(items, f"hollow_bow_pulling_{i}.png"))
    spawn_egg((24, 21, 28), (140, 70, 210)).save(os.path.join(items, "hollow_hunter_spawn_egg.png"))
    spawn_egg((74, 64, 56), (110, 70, 150)).save(os.path.join(items, "collector_spawn_egg.png"))

    eff = os.path.join(ASSETS, "textures/mob_effect")
    os.makedirs(eff, exist_ok=True)
    effect_icon().save(os.path.join(eff, "hollow_mark.png"))
    print("assets generated")


if __name__ == "__main__":
    main()


# --------------------------------------------------------------------------------------------
# The Collector's jars & bottles (block models + textures + blockstates + loot)
# --------------------------------------------------------------------------------------------
import json


def tex_fill(fn, seed):
    rng = random.Random(seed)
    img = Image.new("RGBA", (16, 16), TRANSPARENT)
    for y in range(16):
        for x in range(16):
            c = fn(x, y, rng)
            if c is not None:
                img.putpixel((x, y), c)
    return img


def glass(x, y, rng):
    if x in (2, 3) or (x == 12 and y % 3 == 0):
        return (235, 240, 250, 150)            # highlight streaks
    if x in (0, 15) or y in (0, 15):
        return (170, 185, 200, 135)            # thicker edges
    return (185, 200, 215, 60 + rng.randrange(20))


def dusty(x, y, rng):
    base = glass(x, y, rng)
    if rng.random() < 0.45:
        return (120, 110, 95, 150 + rng.randrange(40))
    return (base[0] - 40, base[1] - 45, base[2] - 50, min(255, base[3] + 50))


def liquid(rgb, alpha=215, speck=None):
    def f(x, y, rng):
        if speck and rng.random() < 0.08:
            return (*speck, 255)
        return (*shade(rgb, 0.85 + rng.random() * 0.3), alpha)
    return f


def solid(palette):
    return lambda x, y, rng: (*pick(rng, palette), 255)


def cloth_lid(x, y, rng):
    if y in (13, 14):
        return (150, 130, 90, 255)
    return (*pick(rng, [(70, 40, 90), (60, 34, 78), (80, 48, 102)]), 255)


def eye(x, y, rng):
    d = math.hypot(x - 7.5, y - 7.5)
    if d < 2.5:
        return (40, 10, 60, 255)
    if d < 4.5:
        return (150, 70, 210, 255)
    return (226, 222, 210, 255)


def label(x, y, rng):
    if x in (0, 15) or y in (0, 15):
        return (150, 130, 95, 255)
    if y in (4, 7, 10) and 2 < x < 13 and rng.random() < 0.7:
        return (70, 50, 40, 255)
    return (*pick(rng, PARCHMENT), 255)


JAR_TEXTURES = {
    "jar_glass": glass,
    "jar_glass_dusty": dusty,
    "jar_cork": solid([(150, 112, 70), (136, 100, 60), (162, 124, 80), (120, 88, 52)]),
    "jar_cloth": cloth_lid,
    "jar_metal": solid([(80, 82, 90), (70, 72, 80), (92, 94, 102)]),
    "liquid_soul": liquid((96, 34, 160), 200, speck=(220, 170, 255)),
    "soul_wisp": solid([(225, 175, 255), (205, 140, 255), (240, 210, 255)]),
    "liquid_specimen": liquid((74, 98, 52), 190, speck=(150, 160, 90)),
    "specimen_eye": eye,
    "jar_label": label,
    "potion_red": liquid((170, 30, 50), 225),
    "potion_teal": liquid((30, 150, 150), 225),
    "potion_purple": liquid((110, 40, 170), 225, speck=(200, 150, 255)),
}


def el(frm, to, texture, light=None, faces=("north", "south", "east", "west", "up", "down")):
    e = {"from": list(frm), "to": list(to), "faces": {f: {"texture": "#" + texture} for f in faces}}
    if light:
        e["light_emission"] = light
    return e


def bottle(x, z, w, h, liquid_tex, light=None):
    """Small corked bottle standing at (x,z) with body w x h."""
    n = 1.0
    cx, cz = x + w / 2, z + w / 2
    return [
        el((x + 0.4, 0.3, z + 0.4), (x + w - 0.4, h - 0.8, z + w - 0.4), liquid_tex, light),
        el((x, 0, z), (x + w, h, z + w), "glass"),
        el((cx - n / 2, h, cz - n / 2), (cx + n / 2, h + 2, cz + n / 2), "glass"),
        el((cx - 0.7, h + 2, cz - 0.7), (cx + 0.7, h + 3, cz + 0.7), "cork"),
    ]


JARS = {
    "soul_jar": ({"glass": "jar_glass", "cork": "jar_cork", "liquid": "liquid_soul", "wisp": "soul_wisp"}, [
        el((4.5, 0.5, 4.5), (11.5, 3, 11.5), "liquid", 10),
        el((7, 3.5, 7), (9, 6.5, 9), "wisp", 15),
        el((6, 6.5, 8), (7, 7.5, 9), "wisp", 15),
        el((4, 0, 4), (12, 9, 12), "glass"),
        el((5, 9, 5), (11, 10, 11), "glass"),
        el((5.5, 10, 5.5), (10.5, 11.5, 10.5), "cork"),
    ]),
    "specimen_jar": ({"glass": "jar_glass", "lid": "jar_metal", "liquid": "liquid_specimen", "eye": "specimen_eye", "label": "jar_label"}, [
        el((3.5, 0.5, 3.5), (12.5, 10, 12.5), "liquid"),
        el((6.5, 4, 6.5), (9.5, 7, 9.5), "eye"),
        el((3, 0, 3), (13, 12, 13), "glass"),
        el((3.5, 12, 3.5), (12.5, 13, 12.5), "lid"),
        el((4.5, 3, 2.95), (11.5, 8, 3), "label", faces=("north",)),
    ]),
    "dusty_jar": ({"glass": "jar_glass_dusty", "cloth": "jar_cloth", "cork": "jar_cork"}, [
        el((4, 0, 4), (12, 8, 12), "glass"),
        el((3.5, 7.5, 3.5), (12.5, 9, 12.5), "cloth"),
        el((3.8, 6.8, 3.8), (12.2, 7.5, 12.2), "cork"),
    ]),
    "tall_potion": ({"glass": "jar_glass", "cork": "jar_cork", "liquid": "potion_purple"}, [
        el((4.5, 0.5, 4.5), (11.5, 5.5, 11.5), "liquid", 6),
        el((4, 0, 4), (12, 6, 12), "glass"),
        el((7.4, 6, 7.4), (8.6, 10, 8.6), "liquid", 6),
        el((7, 6, 7), (9, 12, 9), "glass"),
        el((6.5, 12, 6.5), (9.5, 14, 9.5), "cork"),
    ]),
    "potion_bottles": ({"glass": "jar_glass", "cork": "jar_cork", "red": "potion_red", "teal": "potion_teal", "purple": "potion_purple"},
        bottle(2, 2, 4, 5, "red") + bottle(9, 3, 4, 6, "teal") + bottle(5, 9, 4, 4, "purple", 4)),
}

JAR_NAMES = {
    "soul_jar": "Soul Jar", "specimen_jar": "Specimen Jar", "dusty_jar": "Dusty Jar",
    "tall_potion": "Tall Potion", "potion_bottles": "Old Potion Bottles",
}


def jar_assets():
    tdir = os.path.join(ASSETS, "textures/block")
    os.makedirs(tdir, exist_ok=True)
    for i, (name, fn) in enumerate(JAR_TEXTURES.items()):
        tex_fill(fn, 100 + i).save(os.path.join(tdir, name + ".png"))

    for d in ("models/block", "blockstates", "items"):
        os.makedirs(os.path.join(ASSETS, d), exist_ok=True)
    loot_dir = os.path.join(ROOT, "src/main/resources/data/underworld/loot_table/blocks")
    os.makedirs(loot_dir, exist_ok=True)

    for name, (textures, elements) in JARS.items():
        tex = {k: "underworld:block/" + v for k, v in textures.items()}
        tex["particle"] = tex["glass"]
        model = {"parent": "minecraft:block/block", "ambientocclusion": False, "textures": tex, "elements": elements}
        json.dump(model, open(os.path.join(ASSETS, "models/block", name + ".json"), "w"), indent=1)
        variants = {f"facing={f}": ({"model": f"underworld:block/{name}", "y": r} if r else {"model": f"underworld:block/{name}"})
                    for f, r in (("north", 0), ("east", 90), ("south", 180), ("west", 270))}
        json.dump({"variants": variants}, open(os.path.join(ASSETS, "blockstates", name + ".json"), "w"), indent=2)
        json.dump({"model": {"type": "minecraft:model", "model": f"underworld:block/{name}"}},
                  open(os.path.join(ASSETS, "items", name + ".json"), "w"), indent=2)
        json.dump({"type": "minecraft:block", "pools": [{"rolls": 1, "conditions": [{"condition": "minecraft:survives_explosion"}],
                   "entries": [{"type": "minecraft:item", "name": f"underworld:{name}"}]}]},
                  open(os.path.join(loot_dir, name + ".json"), "w"), indent=2)

    lang_path = os.path.join(ASSETS, "lang/en_us.json")
    lang = json.load(open(lang_path)) if os.path.exists(lang_path) else {}
    for name, title in JAR_NAMES.items():
        lang[f"block.underworld.{name}"] = title
    json.dump(lang, open(lang_path, "w"), indent=2)
    print("jar assets generated")


if __name__ == "__main__":
    jar_assets()
